#!/usr/bin/env bash
set -e

init_marker=$HOME/.dotbot.initialize
if test -f "$init_marker"; then
  echo "=== Init marker detected, skipping init ==="
  return 0
fi

# Boilerplate dotbot script below
CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${BASEDIR}"

# Bring in codespaces environment
source "./codespaces/install"

git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

# Switch to bash shell by default
sudo chsh -s $(which bash) $(whoami)

# Mark that dotbot has been initialized
touch "$init_marker"
